# -*- coding: utf-8 -*-
"""Calc12_1_SRM709LeadOxideGlass

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PEH15SiA7cLQ3hRSB6-HM_1A1_RfcZa
"""

#This code models the frequency-dependence of dielectric properties a LeadOxide Glass
#Inputs: B_ep1, C_ep1, D_ep1, G_ep1, H_ep1, I_ep1, and J_ep1, and f_min
#Outputs: .csv file with real and imaginary epsilon values


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


#define material properties
material_name = 'LeadOxideGlass'


B_ep1 = (4.0905) - (1.73E-002j)
C_ep1 = (4.0905) - (1.73E-002j)
D_ep1 = (2E-004) - (3.1E-003j)
G_ep1 = (4.0905) - (1.75E-002j)
H_ep1 = (1E-004) - (1.4E-003j)
I_ep1 = (7.4E-003) + (4E-003j)
J_ep1 = (5E-004) - (6E-004j)


#frequency range
f_min = 0.2
f_max = 10
num_points = 100 - 1
frequencies = np.linspace(f_min, f_max, num_points)


#permittivity epsilon(f)
epsilon_f = B_ep1 + (2 * C_ep1 * (frequencies ** D_ep1)) + (G_ep1 * (1 - J_ep1 * ((frequencies - H_ep1)**2) - 1j * 2 * I_ep1 * frequencies)**(-1))


#permiability: mu = 1, for non-magnetic materials
mu_f = 1


#export data
data = {
    'Frequency_Hz': frequencies,
    'Real_Epsilon': np.real(epsilon_f),
    'Imag_Epsilon': np.imag(epsilon_f),
    'Mu': mu_f
}
data_table = pd.DataFrame(data)


file_name = f'{material_name}.csv'
data_table.to_csv(file_name, index=False)
print(f'Data exported to {file_name}')


#loglog plot
plt.figure()
plt.loglog(frequencies, np.real(epsilon_f), 'b-', linewidth=2, label='Re(Eps)')
plt.loglog(frequencies, np.imag(epsilon_f), 'r--', linewidth=2, label='Im(Eps)')
plt.xlabel('Frequency [GHz]', fontsize=12)
plt.ylabel('Epsilon', fontsize=12)
plt.legend(loc='best')
plt.grid(True, which="both", ls="--")
plt.title('Real and Imaginary Permittivity vs. Frequency', fontsize=14)
plt.xlim(1e-1, 1e3)
plt.ylim(1e-4, 10)
plt.show()